#!/bin/bash
set -e

GOPATH=/tmp/longhorn-orchestration
mkdir -p $GOPATH/src/github.com/rancher
cd $GOPATH/src/github.com/rancher

if [ -n "${LONGHORN_ORCHESTRATION_DEV_DIR}" ]; then
    cp -r ${LONGHORN_ORCHESTRATION_DEV_DIR} longhorn-orchestration
    cd longhorn-orchestration
else
    git clone ${LONGHORN_ORCHESTRATION_URL}
    cd longhorn-orchestration
    git checkout -q ${LONGHORN_ORCHESTRATION_COMMIT}
fi

go build -o /usr/local/bin/longhorn-orchestration
